# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'TinyShop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TinyShop
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'MJExtension'
pod 'Masonry'
pod ‘MBProgressHUD’
end
